# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='body',
        ),
        migrations.RemoveField(
            model_name='order',
            name='syma',
        ),
    ]
