# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170816_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='\u0426\u0456\u043d\u0430')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='\u041a\u0456\u043b\u044c\u043a\u0456\u0441\u0442\u044c')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Flower')),
            ],
        ),
    ]
