# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.TextField(blank=True),
        ),
    ]
